### ISSUE TITLE
At random points, remote will crash with "Broken Pipe" error

### ISSUE THREAD

**Issue by hqnna** [driplet/remote#2]
![img](https://cdn.discordapp.com/attachments/516895872626196490/561761008209887232/unknown.png)

**Comment by adityaxdiwakar** [comment]
A little about the design of the websocket plays a factor into this:

When you run the remote controller, it makes a request to Driplet and requests all the servers and opens a ``multiprocessing`` Process with a websocket connected for that service. It polls every 15 seconds to see if services were added or removed, and it adds or removes the processes as needed (using ``SIGTERM``).

The issue in this case is the connection between one of those processes (presumably for one of your processes) and our system. Based on the screenshot you provided, it's on the input side as opposed to the receiving side (for start/stop/restart).

I've begun some research of my own to this to investigate on what could be causing the issue, but this is most definitely a high priority issue.

An easy fix to this wil roll out tomorrow, where we'll kill every process and reconnect if an issue like this occurs. However, I'd like to **not** beat around the bush and get to the bottom of this.

Thanks for your bug report.

**Comment by adityaxdiwakar** [comment]
In efforts to mitigate the initial stream of logs that come in when an initial ``stdout`` feed is read, I've added the principle of dupe checking over at daemon@1.0.0, this will be pushed into production very soon.

More about that commit [here](https://github.com/driplet/daemon/commit/2cae4f23b3590a25d42ba8a0c45d8ce021a6ba52)

**Comment by adityaxdiwakar** [comment]
Effective soon, remote@1.0.0 will be deprecated as soon as remote@1.1.0 rolls out in a few hours.
